export const en = {
  common: { appName: 'CareLink', back: 'Back', continue: 'Continue', processing: 'Processing...', loading: 'Loading...', confirm: 'Confirm', search: 'Search', refresh: 'Refresh', noInfo: 'No information', thisMonth: 'This month', lastMonth: 'Last month', all: 'All', step: 'STEP {{current}} / {{total}}' },
  nav: { home: 'Home', prescriptions: 'Prescriptions', community: 'Community', mypage: 'My Page' },
  language: { title: 'Select your language', subtitle: 'Select Your Language', supportPrompt: "Can't find your language?", supportAction: 'Request language support', selected: 'Selected', ko: 'Korean', en: 'English', ja: 'Japanese', zh: 'Chinese', vi: 'Vietnamese', th: 'Thai', uz: 'Uzbek' },
  splash: { subtitle: 'We make medical information easier to understand.' },
  home: { greeting: 'Hello, this is CareLink', symptomTitle: 'Department recommendation', symptomDescription: 'AI analyzes symptoms and recommends the right department.', prescriptionTitle: 'Prescription guide', prescriptionDescription: 'AI reads prescriptions and organizes medication details.', recentPrescription: 'Recent prescription', viewAll: 'View all', emptyPrescription: 'Upload your prescription', prescriptionLabel: 'Prescription', medicineCount: '{{count}} medicines', notifications: 'Notifications' },
  mypage: { title: 'My Page', logout: 'Log out' },
  prescription: {
    listTitle: 'Prescription list', searchPlaceholder: 'Search prescriptions', empty: 'No prescriptions found.', loadFailed: 'Failed to load prescriptions.', recordLabel: 'Prescription', medicineCount: '{{count}} medicines',
    scanTitle: 'Scan prescription', scanInfoTitle: 'Please scan your prescription.', scanInfoDescription: 'AI analyzes the prescription and summarizes key information and dosage instructions.', scanFrameHint: 'Fit the prescription inside the frame', cameraTipTitle: 'Photo tips', cameraTip1: 'Take the photo in a bright place.', cameraTip2: 'Keep the prescription straight and flat.', cameraTip3: 'Focus so the text is clearly visible.', uploadMethod: 'Choose an upload method.', takePhoto: 'Take photo', selectGallery: 'Select from gallery', cancel: 'Cancel', loadingMessage: 'AI is analyzing the prescription',
    resultTitle: 'Prescription translation result', resultHeading: 'Prescription result', resultDescription: 'We read your uploaded prescription and organized the medication details.', summary: 'Prescription summary', totalDrugCount: 'Total medicines', prescribedDate: 'Prescription date', drugList: 'Medication list', dosage: 'Dose per intake', frequency: 'Times per day', duration: 'Total days', description: 'Description', sideEffects: 'Side effects', precautions: 'Precautions', foodInteraction: 'Food caution', handwrittenNote: 'Doctor note', retake: 'Retake', previewAlt: 'Prescription preview', chatbot: 'Chat with AI', chatPlaceholder: 'Ask about your prescription', chatGreeting: 'Hello! Feel free to ask any questions about your prescription.',
  },
  community: {
    title: 'Community', write: 'Write post', postTitle: 'Post', writeTitle: 'Write post', category: 'Category', searchPlaceholder: 'Search', empty: 'No posts found.', notFound: 'Post not found.', commentPlaceholder: 'Write a comment', commentSubmit: 'Post', commentsCount: '{{count}} comments', noComments: 'No comments yet.', commentTag: 'Comment', titleLabel: 'Title', titlePlaceholder: 'Enter a title', contentLabel: 'Content', contentPlaceholder: 'Enter content', posting: 'Posting...', post: 'Post', likeCount: 'Likes',
    categoryLabel: { ALL: 'All', REVIEW: 'Review', NOTICE: 'Hospital info', QUESTION: 'Question', FREE: 'Free talk' },
    timeJustNow: 'Just now', timeMinutesAgo_one: '{{count}} minute ago', timeMinutesAgo_other: '{{count}} minutes ago', timeHoursAgo_one: '{{count}} hour ago', timeHoursAgo_other: '{{count}} hours ago', timeDaysAgo_one: '{{count}} day ago', timeDaysAgo_other: '{{count}} days ago',
  },
  symptom: {
    inputTitle: 'Symptom input', recommendTitle: 'Department recommendation', next: 'Get department recommendation', heading: 'What symptoms do you have?', description: 'Enter your symptoms or select them below.', selected: 'Selected symptoms', selectedEmpty: 'No symptoms selected yet', quickPick: 'Quick symptom selection', customInputTitle: 'Describe symptoms', customInputDescription: 'Please describe your symptoms in as much detail as possible. Example: when it started, where it hurts, and how severe it is.', customInputPlaceholder: 'Enter details', analyzing: 'AI is analyzing your symptoms', analysisDone: 'AI analysis complete', analysisDescription: 'We analyzed your symptoms. Check the most suitable department.', selectedSymptoms: 'Selected symptoms', recommendedDepartment: 'AI recommended department', bestMatch: 'Best match', alternativeDepartments: 'Alternative departments', warningTitle: 'Important notice', warningTooltip: 'Please read and check the notice', warningBody: 'This guidance is based on symptoms and does not replace diagnosis or treatment by a medical professional.', warningAgree: 'I have read the notice above.', checkHospitals: 'Check hospitals', failedTitle: 'Analysis failed', failedReason: 'Failed to analyze symptoms. Please try again.', remove: 'Remove',
    category: { cold: 'Cold and respiratory', pain: 'Pain', fever: 'Fever and body aches', skin: 'Skin issues', digestion: 'Stomach and digestion', ent: 'Ear, nose, and throat', chest: 'Chest and heart' },
  },
  hospitals: { title: 'Nearby hospitals', prepareVisit: 'Prepare for visit', radiusLimit: 'Up to {{limit}} hospitals within {{radius}}km', aiRecommendation: 'AI recommendation: {{department}}', searchPlaceholder: 'Search', fetchFailed: 'Failed to load hospital information.', empty: 'No hospitals found within {{radius}}km.', phoneUnavailable: 'No phone information', websiteUnavailable: 'No website information' },
} as const;
