export const ja = {
  common: { appName: 'CareLink', back: '戻る', continue: '続ける', processing: '処理中...', loading: '読み込み中...', confirm: '確認', search: '検索', refresh: '更新', noInfo: '情報なし', thisMonth: '今月', lastMonth: '先月', all: 'すべて', step: 'STEP {{current}} / {{total}}' },
  nav: { home: 'ホーム', prescriptions: '処方箋', community: 'コミュニティ', mypage: 'マイページ' },
  language: { title: '言語を選択してください', subtitle: 'Select Your Language', supportPrompt: '希望する言語がありませんか？', supportAction: '言語サポートを依頼', selected: '選択済み', ko: '韓国語', en: '英語', ja: '日本語', zh: '中国語', vi: 'ベトナム語', th: 'タイ語', uz: 'ウズベク語' },
  splash: { subtitle: '医療情報をもっとわかりやすくします。' },
  home: { greeting: 'こんにちは', symptomTitle: '診療科おすすめ', symptomDescription: 'AIが症状を分析し、適切な診療科を案内します。', prescriptionTitle: '処方箋案内', prescriptionDescription: 'AIが処方箋を読み取り、服薬情報を整理します。', recentPrescription: '最近の処方箋', viewAll: 'すべて見る', emptyPrescription: '処方箋を登録してみましょう', prescriptionLabel: '処方箋', medicineCount: '薬 {{count}}個', notifications: '通知' },
  mypage: { title: 'マイページ', logout: 'ログアウト' },
  prescription: { listTitle: '処方箋一覧', searchPlaceholder: '処方箋を検索', empty: '処方箋がありません。', loadFailed: '処方箋一覧を読み込めませんでした。', recordLabel: '処方箋', medicineCount: '薬 {{count}}個', scanTitle: '処方箋スキャン', scanInfoTitle: '処方箋をスキャンしてください。', scanInfoDescription: 'AIが処方箋を分析し、重要な情報と服薬方法を整理します。', scanFrameHint: '処方箋を枠の中に合わせてください', cameraTipTitle: '撮影のコツ', cameraTip1: '明るい場所で撮影してください。', cameraTip2: '処方箋がまっすぐ見えるようにしてください。', cameraTip3: '文字がはっきり見えるようにピントを合わせてください。', uploadMethod: 'アップロード方法を選択してください。', takePhoto: '写真を撮る', selectGallery: 'ギャラリーから選択', cancel: 'キャンセル', loadingMessage: 'AIが処方箋を分析中です', resultTitle: '処方箋翻訳結果', resultHeading: '処方箋結果', resultDescription: 'アップロードした処方箋を読み取り、服薬情報を整理しました。', summary: '処方箋の要約', totalDrugCount: '薬の数', prescribedDate: '処方日', drugList: '処方薬一覧', dosage: '1回の服用量', frequency: '1日の服用回数', duration: '服用日数', description: '説明', sideEffects: '副作用', precautions: '注意事項', foodInteraction: '食事の注意', handwrittenNote: '医師メモ', retake: '撮り直す', previewAlt: '処方箋プレビュー', chatbot: 'AIと話す', chatPlaceholder: '処方箋について質問する', chatGreeting: 'こんにちは。処方箋についてご質問があればお気軽にどうぞ。' },
  community: { title: 'コミュニティ', write: '投稿する', postTitle: '投稿', writeTitle: '投稿作成', category: 'カテゴリー', searchPlaceholder: '検索', empty: '投稿がありません。', notFound: '投稿が見つかりません。', commentPlaceholder: 'コメントを入力してください', commentSubmit: '登録', commentsCount: 'コメント {{count}}件', noComments: 'まだコメントがありません。', commentTag: 'コメント', titleLabel: 'タイトル', titlePlaceholder: 'タイトルを入力してください', contentLabel: '内容', contentPlaceholder: '内容を入力してください', posting: '投稿中...', post: '投稿する', likeCount: 'いいね', categoryLabel: { ALL: 'すべて', REVIEW: 'レビュー', NOTICE: '病院情報', QUESTION: '質問', FREE: '情報共有' }, timeJustNow: 'たった今', timeMinutesAgo_one: '{{count}}分前', timeMinutesAgo_other: '{{count}}分前', timeHoursAgo_one: '{{count}}時間前', timeHoursAgo_other: '{{count}}時間前', timeDaysAgo_one: '{{count}}日前', timeDaysAgo_other: '{{count}}日前' },
  symptom: { inputTitle: '症状入力', recommendTitle: '診療科おすすめ', next: '診療科のおすすめを見る', heading: 'どんな症状がありますか？', description: '症状を入力するか、下から選択してください。', selected: '選択した症状', selectedEmpty: 'まだ選択した症状はありません', quickPick: 'よくある症状を選ぶ', customInputTitle: '症状を入力する', customInputDescription: '症状をできるだけ詳しく入力してください。例: いつから、どこが、どれくらい痛いか', customInputPlaceholder: '内容を入力してください', analyzing: 'AIが症状を分析中です', analysisDone: 'AI分析完了', analysisDescription: '入力した症状を分析しました。最も適した診療科を確認してください。', selectedSymptoms: '選択した症状', recommendedDepartment: 'AIおすすめ診療科', bestMatch: '最適マッチ', alternativeDepartments: '他の候補', warningTitle: '注意事項', warningTooltip: '注意事項を読んでチェックしてください', warningBody: 'この案内は症状に基づく参考情報であり、医療従事者の診断や治療に代わるものではありません。', warningAgree: '上記の注意事項を確認しました。', checkHospitals: '病院を確認する', failedTitle: '分析失敗', failedReason: '症状の分析に失敗しました。もう一度お試しください。', remove: '削除', category: { cold: '風邪・呼吸器', pain: '痛み', fever: '発熱・体のだるさ', skin: '皮膚の問題', digestion: '腹痛・消化', ent: '耳鼻咽喉科', chest: '胸・心臓' } },
  hospitals: { title: '近くの病院', prepareVisit: '受診の準備', radiusLimit: '半径 {{radius}}km 以内 最大 {{limit}}件', aiRecommendation: 'AIおすすめ: {{department}}', searchPlaceholder: '検索', fetchFailed: '病院情報を読み込めませんでした。', empty: '半径 {{radius}}km 内に病院がありません。', phoneUnavailable: '電話情報なし', websiteUnavailable: 'ホームページ情報なし' },
} as const;
