export const th = {
  common: { appName: 'CareLink', back: 'ย้อนกลับ', continue: 'ดำเนินการต่อ', processing: 'กำลังประมวลผล...', loading: 'กำลังโหลด...', confirm: 'ยืนยัน', search: 'ค้นหา', refresh: 'รีเฟรช', noInfo: 'ไม่มีข้อมูล', thisMonth: 'เดือนนี้', lastMonth: 'เดือนที่แล้ว', all: 'ทั้งหมด', step: 'STEP {{current}} / {{total}}' },
  nav: { home: 'หน้าแรก', prescriptions: 'ใบสั่งยา', community: 'ชุมชน', mypage: 'หน้าของฉัน' },
  language: { title: 'กรุณาเลือกภาษา', subtitle: 'Select Your Language', supportPrompt: 'ไม่พบภาษาที่ต้องการใช่ไหม?', supportAction: 'ขอเพิ่มการรองรับภาษา', selected: 'เลือกแล้ว', ko: 'เกาหลี', en: 'อังกฤษ', ja: 'ญี่ปุ่น', zh: 'จีน', vi: 'เวียดนาม', th: 'ไทย', uz: 'อุซเบก' },
  splash: { subtitle: 'ทำให้ข้อมูลทางการแพทย์เข้าใจง่ายขึ้น' },
  home: { greeting: 'สวัสดี นี่คือ', symptomTitle: 'แนะนำแผนก', symptomDescription: 'AI วิเคราะห์อาการและแนะนำแผนกที่เหมาะสม', prescriptionTitle: 'คำแนะนำใบสั่งยา', prescriptionDescription: 'AI อ่านใบสั่งยาและจัดข้อมูลการใช้ยาให้', recentPrescription: 'ใบสั่งยาล่าสุด', viewAll: 'ดูทั้งหมด', emptyPrescription: 'ลองอัปโหลดใบสั่งยา', prescriptionLabel: 'ใบสั่งยา', medicineCount: 'ยา {{count}} รายการ', notifications: 'การแจ้งเตือน' },
  mypage: { title: 'หน้าของฉัน', logout: 'ออกจากระบบ' },
  prescription: { listTitle: 'รายการใบสั่งยา', searchPlaceholder: 'ค้นหาใบสั่งยา', empty: 'ไม่มีใบสั่งยา', loadFailed: 'ไม่สามารถโหลดรายการใบสั่งยาได้', recordLabel: 'ใบสั่งยา', medicineCount: 'ยา {{count}} รายการ', scanTitle: 'สแกนใบสั่งยา', scanInfoTitle: 'กรุณาสแกนใบสั่งยา', scanInfoDescription: 'AI จะวิเคราะห์ใบสั่งยาและสรุปข้อมูลสำคัญพร้อมวิธีใช้ยา', scanFrameHint: 'จัดใบสั่งยาให้อยู่ในกรอบ', cameraTipTitle: 'คำแนะนำการถ่ายภาพ', cameraTip1: 'ถ่ายในที่ที่มีแสงเพียงพอ', cameraTip2: 'จัดใบสั่งยาให้ตรงและเรียบ', cameraTip3: 'โฟกัสให้ตัวอักษรชัดเจน', uploadMethod: 'เลือกวิธีอัปโหลด', takePhoto: 'ถ่ายรูป', selectGallery: 'เลือกจากแกลเลอรี', cancel: 'ยกเลิก', loadingMessage: 'AI กำลังวิเคราะห์ใบสั่งยา', resultTitle: 'ผลการแปลใบสั่งยา', resultHeading: 'ผลลัพธ์ใบสั่งยา', resultDescription: 'เราอ่านใบสั่งยาที่อัปโหลดและจัดข้อมูลการใช้ยาแล้ว', summary: 'สรุปใบสั่งยา', totalDrugCount: 'จำนวนยา', prescribedDate: 'วันที่สั่งยา', drugList: 'รายการยา', dosage: 'ปริมาณต่อครั้ง', frequency: 'จำนวนครั้งต่อวัน', duration: 'จำนวนวันทั้งหมด', description: 'คำอธิบาย', sideEffects: 'ผลข้างเคียง', precautions: 'ข้อควรระวัง', foodInteraction: 'ข้อควรระวังเรื่องอาหาร', handwrittenNote: 'บันทึกจากแพทย์', retake: 'ถ่ายใหม่', previewAlt: 'ตัวอย่างใบสั่งยา', chatbot: 'คุยกับ AI', chatPlaceholder: 'พิมพ์คำถามเกี่ยวกับใบสั่งยา', chatGreeting: 'สวัสดีครับ! สอบถามเกี่ยวกับใบสั่งยาของคุณได้เลย' },
  community: { title: 'ชุมชน', write: 'เขียนโพสต์', postTitle: 'โพสต์', writeTitle: 'เขียนโพสต์', category: 'หมวดหมู่', searchPlaceholder: 'ค้นหา', empty: 'ไม่มีโพสต์', notFound: 'ไม่พบโพสต์', commentPlaceholder: 'กรอกความคิดเห็น', commentSubmit: 'โพสต์', commentsCount: '{{count}} ความคิดเห็น', noComments: 'ยังไม่มีความคิดเห็น', commentTag: 'ความคิดเห็น', titleLabel: 'หัวข้อ', titlePlaceholder: 'กรอกหัวข้อ', contentLabel: 'เนื้อหา', contentPlaceholder: 'กรอกเนื้อหา', posting: 'กำลังโพสต์...', post: 'โพสต์', likeCount: 'ถูกใจ', categoryLabel: { ALL: 'ทั้งหมด', REVIEW: 'รีวิว', NOTICE: 'ข้อมูลโรงพยาบาล', QUESTION: 'คำถาม', FREE: 'แชร์ข้อมูล' }, timeJustNow: 'เมื่อสักครู่', timeMinutesAgo_one: '{{count}} นาทีที่แล้ว', timeMinutesAgo_other: '{{count}} นาทีที่แล้ว', timeHoursAgo_one: '{{count}} ชั่วโมงที่แล้ว', timeHoursAgo_other: '{{count}} ชั่วโมงที่แล้ว', timeDaysAgo_one: '{{count}} วันที่แล้ว', timeDaysAgo_other: '{{count}} วันที่แล้ว' },
  symptom: { inputTitle: 'กรอกอาการ', recommendTitle: 'แนะนำแผนก', next: 'รับคำแนะนำแผนก', heading: 'คุณมีอาการอะไรบ้าง?', description: 'กรอกอาการหรือเลือกจากด้านล่าง', selected: 'อาการที่เลือก', selectedEmpty: 'ยังไม่ได้เลือกอาการ', quickPick: 'เลือกอาการด่วน', customInputTitle: 'กรอกอาการ', customInputDescription: 'กรุณาอธิบายอาการให้ละเอียดที่สุด เช่น เริ่มเมื่อไร เจ็บตรงไหน และรุนแรงแค่ไหน', customInputPlaceholder: 'กรอกเนื้อหา', analyzing: 'AI กำลังวิเคราะห์อาการ', analysisDone: 'AI วิเคราะห์เสร็จแล้ว', analysisDescription: 'เราได้วิเคราะห์อาการของคุณแล้ว โปรดตรวจสอบแผนกที่เหมาะสมที่สุด', selectedSymptoms: 'อาการที่เลือก', recommendedDepartment: 'แผนกที่ AI แนะนำ', bestMatch: 'เหมาะสมที่สุด', alternativeDepartments: 'แผนกทางเลือก', warningTitle: 'ข้อควรระวัง', warningTooltip: 'กรุณาอ่านและทำเครื่องหมายข้อควรระวัง', warningBody: 'ข้อมูลนี้เป็นเพียงคำแนะนำตามอาการ และไม่สามารถแทนการวินิจฉัยหรือการรักษาจากบุคลากรทางการแพทย์ได้', warningAgree: 'ฉันได้อ่านข้อควรระวังข้างต้นแล้ว', checkHospitals: 'ดูโรงพยาบาล', failedTitle: 'วิเคราะห์ไม่สำเร็จ', failedReason: 'การวิเคราะห์อาการล้มเหลว กรุณาลองใหม่อีกครั้ง', remove: 'ลบ', category: { cold: 'หวัดและระบบทางเดินหายใจ', pain: 'อาการปวด', fever: 'ไข้และปวดเมื่อย', skin: 'ปัญหาผิวหนัง', digestion: 'ปวดท้องและการย่อย', ent: 'หู คอ จมูก', chest: 'หน้าอกและหัวใจ' } },
  hospitals: { title: 'โรงพยาบาลใกล้ฉัน', prepareVisit: 'เตรียมตัวไปพบแพทย์', radiusLimit: 'ภายใน {{radius}} กม. สูงสุด {{limit}} แห่ง', aiRecommendation: 'AI แนะนำ: {{department}}', searchPlaceholder: 'ค้นหา', fetchFailed: 'ไม่สามารถโหลดข้อมูลโรงพยาบาลได้', empty: 'ไม่พบโรงพยาบาลในระยะ {{radius}} กม.', phoneUnavailable: 'ไม่มีข้อมูลโทรศัพท์', websiteUnavailable: 'ไม่มีข้อมูลเว็บไซต์' },
} as const;
