export const uz = {
  common: { appName: 'CareLink', back: 'Orqaga', continue: 'Davom etish', processing: 'Qayta ishlanmoqda...', loading: 'Yuklanmoqda...', confirm: 'Tasdiqlash', search: 'Qidirish', refresh: 'Yangilash', noInfo: "Ma'lumot yo'q", thisMonth: 'Bu oy', lastMonth: "O'tgan oy", all: 'Barchasi', step: 'STEP {{current}} / {{total}}' },
  nav: { home: 'Bosh sahifa', prescriptions: 'Retseptlar', community: 'Hamjamiyat', mypage: 'Mening sahifam' },
  language: { title: 'Tilni tanlang', subtitle: 'Select Your Language', supportPrompt: 'Kerakli til topilmadimi?', supportAction: "Til qo'llab-quvvatlashini so'rash", selected: 'Tanlangan', ko: 'Koreyscha', en: 'Inglizcha', ja: 'Yaponcha', zh: 'Xitoycha', vi: 'Vetnamcha', th: 'Taycha', uz: "O'zbek tili" },
  splash: { subtitle: "Tibbiy ma'lumotni tushunishni osonlashtiramiz." },
  home: { greeting: 'Salom, bu CareLink', symptomTitle: "Bo'lim tavsiyasi", symptomDescription: "AI simptomlarni tahlil qiladi va mos bo'limni tavsiya qiladi.", prescriptionTitle: "Retsept bo'yicha yo'riqnoma", prescriptionDescription: "AI retseptni o'qiydi va dori ma'lumotlarini tartiblaydi.", recentPrescription: "So'nggi retsept", viewAll: "Hammasini ko'rish", emptyPrescription: "Retsept yuklab ko'ring", prescriptionLabel: 'Retsept', medicineCount: '{{count}} ta dori', notifications: 'Bildirishnomalar' },
  mypage: { title: 'Mening sahifam', logout: 'Chiqish' },
  prescription: { listTitle: "Retseptlar ro'yxati", searchPlaceholder: 'Retsept qidirish', empty: "Retsept yo'q.", loadFailed: "Retseptlar ro'yxatini yuklab bo'lmadi.", recordLabel: 'Retsept', medicineCount: '{{count}} ta dori', scanTitle: 'Retseptni skanerlash', scanInfoTitle: 'Retseptni skanerlang.', scanInfoDescription: "AI retseptni tahlil qiladi va asosiy ma'lumotlar hamda qabul qilish usulini jamlaydi.", scanFrameHint: 'Retseptni ramka ichiga moslashtiring', cameraTipTitle: "Suratga olish bo'yicha maslahatlar", cameraTip1: "Yorug' joyda suratga oling.", cameraTip2: "Retsept tekis va to'g'ri ko'rinsin.", cameraTip3: "Matn aniq ko'rinishi uchun fokuslang.", uploadMethod: 'Yuklash usulini tanlang.', takePhoto: 'Rasmga olish', selectGallery: 'Galereyadan tanlash', cancel: 'Bekor qilish', loadingMessage: 'AI retseptni tahlil qilmoqda', resultTitle: 'Retsept tarjimasi natijasi', resultHeading: 'Retsept natijasi', resultDescription: "Yuklangan retsept o'qildi va dori qabul qilish ma'lumoti tartiblandi.", summary: 'Retsept xulosasi', totalDrugCount: 'Dori soni', prescribedDate: 'Yozilgan sana', drugList: "Dorilar ro'yxati", dosage: 'Bir martalik miqdor', frequency: 'Kuniga necha marta', duration: 'Jami kunlar', description: 'Izoh', sideEffects: "Nojo'ya ta'sirlar", precautions: 'Ogohlantirishlar', foodInteraction: "Ovqat bo'yicha ehtiyot", handwrittenNote: 'Shifokor izohi', retake: 'Qayta suratga olish', previewAlt: "Retsept ko'rinishi", chatbot: 'AI bilan suhbat', chatPlaceholder: 'Retsept haqida savol yozing', chatGreeting: 'Salom! Retsept haqida istalgan savolingizni bering.' },
  community: { title: 'Hamjamiyat', write: 'Post yozish', postTitle: 'Post', writeTitle: 'Post yozish', category: 'Kategoriya', searchPlaceholder: 'Qidirish', empty: "Postlar yo'q.", notFound: 'Post topilmadi.', commentPlaceholder: 'Izoh yozing', commentSubmit: "Jo'natish", commentsCount: '{{count}} ta izoh', noComments: "Hali izoh yo'q.", commentTag: 'Izoh', titleLabel: 'Sarlavha', titlePlaceholder: 'Sarlavha kiriting', contentLabel: 'Mazmun', contentPlaceholder: 'Mazmun kiriting', posting: 'Joylanmoqda...', post: 'Joylash', likeCount: 'Layklar', categoryLabel: { ALL: 'Barchasi', REVIEW: 'Sharh', NOTICE: "Shifoxona ma'lumoti", QUESTION: 'Savol', FREE: "Ma'lumot ulashish" }, timeJustNow: 'Hozirgina', timeMinutesAgo_one: '{{count}} daqiqa oldin', timeMinutesAgo_other: '{{count}} daqiqa oldin', timeHoursAgo_one: '{{count}} soat oldin', timeHoursAgo_other: '{{count}} soat oldin', timeDaysAgo_one: '{{count}} kun oldin', timeDaysAgo_other: '{{count}} kun oldin' },
  symptom: { inputTitle: 'Simptom kiritish', recommendTitle: "Bo'lim tavsiyasi", next: "Bo'lim tavsiyasini olish", heading: 'Qanday simptomlaringiz bor?', description: 'Simptomlarni kiriting yoki quyidagilardan tanlang.', selected: 'Tanlangan simptomlar', selectedEmpty: 'Hali simptom tanlanmagan', quickPick: 'Tez tanlash', customInputTitle: 'Simptomlarni kiriting', customInputDescription: "Iltimos, simptomlarni iloji boricha batafsil yozing. Masalan: qachondan beri, qayeri og'riyapti, qanchalik kuchli.", customInputPlaceholder: 'Matn kiriting', analyzing: 'AI simptomlarni tahlil qilmoqda', analysisDone: 'AI tahlili yakunlandi', analysisDescription: "Simptomlaringiz tahlil qilindi. Eng mos bo'limni ko'ring.", selectedSymptoms: 'Tanlangan simptomlar', recommendedDepartment: 'AI tavsiya qilgan bo‘lim', bestMatch: 'Eng mos', alternativeDepartments: "Muqobil bo'limlar", warningTitle: 'Ogohlantirish', warningTooltip: "Iltimos, ogohlantirishni o'qib belgilang", warningBody: "Bu ma'lumot simptomlarga asoslangan tavsiya bo'lib, tibbiy tashxis yoki davolashning o'rnini bosa olmaydi.", warningAgree: "Yuqoridagi ogohlantirishni o'qidim.", checkHospitals: "Shifoxonalarni ko'rish", failedTitle: 'Tahlil muvaffaqiyatsiz', failedReason: "Simptom tahlili muvaffaqiyatsiz tugadi. Qayta urinib ko'ring.", remove: "O'chirish", category: { cold: "Shamollash va nafas yo'llari", pain: "Og'riq", fever: 'Isitma va holsizlik', skin: 'Teri muammolari', digestion: 'Qorin va hazm', ent: 'Quloq, burun, tomoq', chest: "Ko'krak va yurak" } },
  hospitals: { title: 'Yaqin shifoxonalar', prepareVisit: 'Qabulga tayyorgarlik', radiusLimit: '{{radius}} km ichida eng ko‘pi {{limit}} ta', aiRecommendation: 'AI tavsiyasi: {{department}}', searchPlaceholder: 'Qidirish', fetchFailed: "Shifoxona ma'lumotini yuklab bo'lmadi.", empty: '{{radius}} km ichida shifoxona topilmadi.', phoneUnavailable: "Telefon ma'lumoti yo'q", websiteUnavailable: "Sayt ma'lumoti yo'q" },
} as const;
