export const vi = {
  common: { appName: 'CareLink', back: 'Quay lại', continue: 'Tiếp tục', processing: 'Đang xử lý...', loading: 'Đang tải...', confirm: 'Xác nhận', search: 'Tìm kiếm', refresh: 'Làm mới', noInfo: 'Không có thông tin', thisMonth: 'Tháng này', lastMonth: 'Tháng trước', all: 'Tất cả', step: 'STEP {{current}} / {{total}}' },
  nav: { home: 'Trang chủ', prescriptions: 'Đơn thuốc', community: 'Cộng đồng', mypage: 'Trang của tôi' },
  language: { title: 'Hãy chọn ngôn ngữ', subtitle: 'Select Your Language', supportPrompt: 'Không thấy ngôn ngữ bạn cần?', supportAction: 'Yêu cầu hỗ trợ ngôn ngữ', selected: 'Đã chọn', ko: 'Tiếng Hàn', en: 'Tiếng Anh', ja: 'Tiếng Nhật', zh: 'Tiếng Trung', vi: 'Tiếng Việt', th: 'Tiếng Thái', uz: 'Tiếng Uzbek' },
  splash: { subtitle: 'Giúp thông tin y tế dễ hiểu hơn.' },
  home: { greeting: 'Xin chào, đây là CareLink', symptomTitle: 'Gợi ý khoa khám', symptomDescription: 'AI phân tích triệu chứng và gợi ý khoa phù hợp.', prescriptionTitle: 'Hướng dẫn đơn thuốc', prescriptionDescription: 'AI đọc đơn thuốc và sắp xếp thông tin dùng thuốc.', recentPrescription: 'Đơn thuốc gần đây', viewAll: 'Xem tất cả', emptyPrescription: 'Hãy tải đơn thuốc lên', prescriptionLabel: 'Đơn thuốc', medicineCount: '{{count}} loại thuốc', notifications: 'Thông báo' },
  mypage: { title: 'Trang của tôi', logout: 'Đăng xuất' },
  prescription: { listTitle: 'Danh sách đơn thuốc', searchPlaceholder: 'Tìm đơn thuốc', empty: 'Không có đơn thuốc.', loadFailed: 'Không thể tải danh sách đơn thuốc.', recordLabel: 'Đơn thuốc', medicineCount: '{{count}} loại thuốc', scanTitle: 'Quét đơn thuốc', scanInfoTitle: 'Vui lòng quét đơn thuốc.', scanInfoDescription: 'AI sẽ phân tích đơn thuốc và tóm tắt thông tin chính cùng cách dùng.', scanFrameHint: 'Đặt đơn thuốc vào trong khung', cameraTipTitle: 'Mẹo chụp ảnh', cameraTip1: 'Chụp ở nơi đủ sáng.', cameraTip2: 'Giữ đơn thuốc thẳng và phẳng.', cameraTip3: 'Đảm bảo chữ rõ nét.', uploadMethod: 'Chọn cách tải lên.', takePhoto: 'Chụp ảnh', selectGallery: 'Chọn từ thư viện', cancel: 'Hủy', loadingMessage: 'AI đang phân tích đơn thuốc', resultTitle: 'Kết quả dịch đơn thuốc', resultHeading: 'Kết quả đơn thuốc', resultDescription: 'Chúng tôi đã đọc đơn thuốc bạn tải lên và sắp xếp thông tin dùng thuốc.', summary: 'Tóm tắt đơn thuốc', totalDrugCount: 'Tổng số thuốc', prescribedDate: 'Ngày kê đơn', drugList: 'Danh sách thuốc', dosage: 'Liều mỗi lần', frequency: 'Số lần mỗi ngày', duration: 'Tổng số ngày', description: 'Mô tả', sideEffects: 'Tác dụng phụ', precautions: 'Lưu ý', foodInteraction: 'Lưu ý về thức ăn', handwrittenNote: 'Ghi chú bác sĩ', retake: 'Chụp lại', previewAlt: 'Xem trước đơn thuốc', chatbot: 'Chat với AI', chatPlaceholder: 'Nhập câu hỏi về đơn thuốc', chatGreeting: 'Xin chào! Hãy hỏi bất kỳ điều gì về đơn thuốc của bạn.' },
  community: { title: 'Cộng đồng', write: 'Viết bài', postTitle: 'Bài viết', writeTitle: 'Viết bài', category: 'Danh mục', searchPlaceholder: 'Tìm kiếm', empty: 'Không có bài viết.', notFound: 'Không tìm thấy bài viết.', commentPlaceholder: 'Nhập bình luận', commentSubmit: 'Đăng', commentsCount: '{{count}} bình luận', noComments: 'Chưa có bình luận.', commentTag: 'Bình luận', titleLabel: 'Tiêu đề', titlePlaceholder: 'Nhập tiêu đề', contentLabel: 'Nội dung', contentPlaceholder: 'Nhập nội dung', posting: 'Đang đăng...', post: 'Đăng bài', likeCount: 'Lượt thích', categoryLabel: { ALL: 'Tất cả', REVIEW: 'Đánh giá', NOTICE: 'Thông tin bệnh viện', QUESTION: 'Câu hỏi', FREE: 'Chia sẻ' }, timeJustNow: 'Vừa xong', timeMinutesAgo_one: '{{count}} phút trước', timeMinutesAgo_other: '{{count}} phút trước', timeHoursAgo_one: '{{count}} giờ trước', timeHoursAgo_other: '{{count}} giờ trước', timeDaysAgo_one: '{{count}} ngày trước', timeDaysAgo_other: '{{count}} ngày trước' },
  symptom: { inputTitle: 'Nhập triệu chứng', recommendTitle: 'Gợi ý khoa khám', next: 'Nhận gợi ý khoa khám', heading: 'Bạn có triệu chứng nào?', description: 'Nhập triệu chứng hoặc chọn ở bên dưới.', selected: 'Triệu chứng đã chọn', selectedEmpty: 'Chưa chọn triệu chứng nào', quickPick: 'Chọn nhanh triệu chứng', customInputTitle: 'Nhập triệu chứng', customInputDescription: 'Vui lòng mô tả triệu chứng càng chi tiết càng tốt. Ví dụ: bắt đầu từ khi nào, đau ở đâu, đau mức nào.', customInputPlaceholder: 'Nhập nội dung', analyzing: 'AI đang phân tích triệu chứng', analysisDone: 'AI phân tích xong', analysisDescription: 'Chúng tôi đã phân tích triệu chứng của bạn. Hãy xem khoa phù hợp nhất.', selectedSymptoms: 'Triệu chứng đã chọn', recommendedDepartment: 'Khoa do AI đề xuất', bestMatch: 'Phù hợp nhất', alternativeDepartments: 'Khoa thay thế', warningTitle: 'Lưu ý', warningTooltip: 'Vui lòng đọc và đánh dấu lưu ý', warningBody: 'Thông tin này chỉ là hướng dẫn dựa trên triệu chứng và không thay thế chẩn đoán hoặc điều trị y khoa.', warningAgree: 'Tôi đã đọc lưu ý ở trên.', checkHospitals: 'Xem bệnh viện', failedTitle: 'Phân tích thất bại', failedReason: 'Phân tích triệu chứng thất bại. Vui lòng thử lại.', remove: 'Xóa', category: { cold: 'Cảm lạnh và hô hấp', pain: 'Đau nhức', fever: 'Sốt và mệt mỏi', skin: 'Vấn đề da', digestion: 'Đau bụng và tiêu hóa', ent: 'Tai mũi họng', chest: 'Ngực và tim' } },
  hospitals: { title: 'Bệnh viện gần đây', prepareVisit: 'Chuẩn bị đi khám', radiusLimit: 'Trong bán kính {{radius}}km tối đa {{limit}} nơi', aiRecommendation: 'AI gợi ý: {{department}}', searchPlaceholder: 'Tìm kiếm', fetchFailed: 'Không thể tải thông tin bệnh viện.', empty: 'Không có bệnh viện trong phạm vi {{radius}}km.', phoneUnavailable: 'Không có số điện thoại', websiteUnavailable: 'Không có trang web' },
} as const;
