export const zh = {
  common: { appName: 'CareLink', back: '返回', continue: '继续', processing: '处理中...', loading: '加载中...', confirm: '确认', search: '搜索', refresh: '刷新', noInfo: '暂无信息', thisMonth: '本月', lastMonth: '上个月', all: '全部', step: 'STEP {{current}} / {{total}}' },
  nav: { home: '首页', prescriptions: '处方', community: '社区', mypage: '我的页面' },
  language: { title: '请选择语言', subtitle: 'Select Your Language', supportPrompt: '没有想要的语言吗？', supportAction: '申请语言支持', selected: '已选择', ko: '韩语', en: '英语', ja: '日语', zh: '中文', vi: '越南语', th: '泰语', uz: '乌兹别克语' },
  splash: { subtitle: '让医疗信息更容易理解。' },
  home: { greeting: '您好，这里是', symptomTitle: '推荐科室', symptomDescription: 'AI 会分析症状并推荐合适的科室。', prescriptionTitle: '处方说明', prescriptionDescription: 'AI 会读取处方并整理用药信息。', recentPrescription: '最近处方', viewAll: '查看全部', emptyPrescription: '上传您的处方', prescriptionLabel: '处方', medicineCount: '{{count}}种药物', notifications: '通知' },
  mypage: { title: '我的页面', logout: '退出登录' },
  prescription: { listTitle: '处方列表', searchPlaceholder: '搜索处方', empty: '暂无处方。', loadFailed: '无法加载处方列表。', recordLabel: '处方', medicineCount: '{{count}}种药物', scanTitle: '扫描处方', scanInfoTitle: '请扫描您的处方。', scanInfoDescription: 'AI 会分析处方并整理关键信息和用药方法。', scanFrameHint: '请将处方放入框内', cameraTipTitle: '拍摄提示', cameraTip1: '请在明亮处拍摄。', cameraTip2: '请保持处方平整端正。', cameraTip3: '请对焦清晰，确保文字可见。', uploadMethod: '请选择上传方式。', takePhoto: '拍照', selectGallery: '从相册选择', cancel: '取消', loadingMessage: 'AI 正在分析处方', resultTitle: '处方翻译结果', resultHeading: '处方结果', resultDescription: '我们已读取您上传的处方并整理了用药信息。', summary: '处方摘要', totalDrugCount: '药物总数', prescribedDate: '开方日期', drugList: '药物列表', dosage: '每次剂量', frequency: '每日次数', duration: '总天数', description: '说明', sideEffects: '副作用', precautions: '注意事项', foodInteraction: '饮食注意', handwrittenNote: '医生备注', retake: '重新拍摄', previewAlt: '处方预览', chatbot: '与AI对话', chatPlaceholder: '请输入您的问题', chatGreeting: '您好！欢迎随时提问关于处方的问题。' },
  community: { title: '社区', write: '写帖子', postTitle: '帖子', writeTitle: '写帖子', category: '分类', searchPlaceholder: '搜索', empty: '暂无帖子。', notFound: '未找到帖子。', commentPlaceholder: '请输入评论', commentSubmit: '发布', commentsCount: '{{count}}条评论', noComments: '暂无评论。', commentTag: '评论', titleLabel: '标题', titlePlaceholder: '请输入标题', contentLabel: '内容', contentPlaceholder: '请输入内容', posting: '发布中...', post: '发布', likeCount: '点赞', categoryLabel: { ALL: '全部', REVIEW: '评价', NOTICE: '医院信息', QUESTION: '提问', FREE: '信息分享' }, timeJustNow: '刚刚', timeMinutesAgo_one: '{{count}}分钟前', timeMinutesAgo_other: '{{count}}分钟前', timeHoursAgo_one: '{{count}}小时前', timeHoursAgo_other: '{{count}}小时前', timeDaysAgo_one: '{{count}}天前', timeDaysAgo_other: '{{count}}天前' },
  symptom: { inputTitle: '输入症状', recommendTitle: '推荐科室', next: '获取科室推荐', heading: '您有哪些症状？', description: '请输入症状，或从下方选择。', selected: '已选择症状', selectedEmpty: '尚未选择症状', quickPick: '快速选择症状', customInputTitle: '输入症状', customInputDescription: '请尽量详细描述症状。例如：从什么时候开始、哪里疼、疼痛程度如何。', customInputPlaceholder: '请输入内容', analyzing: 'AI 正在分析症状', analysisDone: 'AI 分析完成', analysisDescription: '已完成对症状的分析。请查看最合适的科室。', selectedSymptoms: '已选择症状', recommendedDepartment: 'AI 推荐科室', bestMatch: '最佳匹配', alternativeDepartments: '其他科室', warningTitle: '注意事项', warningTooltip: '请阅读并勾选注意事项', warningBody: '本提示基于症状提供参考信息，不能替代专业医护人员的诊断或治疗。', warningAgree: '我已阅读上述注意事项。', checkHospitals: '查看医院', failedTitle: '分析失败', failedReason: '症状分析失败，请重试。', remove: '移除', category: { cold: '感冒与呼吸道', pain: '疼痛', fever: '发热与酸痛', skin: '皮肤问题', digestion: '腹痛与消化', ent: '耳鼻喉', chest: '胸部与心脏' } },
  hospitals: { title: '附近医院', prepareVisit: '就诊准备', radiusLimit: '{{radius}}公里内最多 {{limit}} 家', aiRecommendation: 'AI 推荐：{{department}}', searchPlaceholder: '搜索', fetchFailed: '无法加载医院信息。', empty: '{{radius}}公里内暂无医院。', phoneUnavailable: '暂无电话信息', websiteUnavailable: '暂无网站信息' },
} as const;
